// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejfwrofizwitkmgsctsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZndyb2ZpendpdGttZ3NjdHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzU3OTEsImV4cCI6MjA3NDQ1MTc5MX0.2_577NK_xd5Mow4ZBQ5zlSteQ1uIaijlFTJV5XjvlEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});